### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by bluechipps** [jameshnsears/QuoteUnquote#10]
Version: 2.8.0-googleplay

**Describe the bug**
Not sure how long ago it was but sometime last year the randomize button stopped randomizing and instead behaves identical to the sequential button. I assumed til now that it was probably my local data's fault. I have uninstalled, verified that /data/data/com.github.jameshnsears.quoteunquote no longer exists in root storage, and reinstalled with no luck. Please advise if there is anything else I could try on my end. Cheers

Galaxy S21 Ultra (SM-G998U)

**Comment by jameshnsears** [comment]
Hi - sorry for the delay in replying. I'll investigate this issue, but on the surface it's not something I'm seeing.

**Comment by jameshnsears** [comment]
OK, there is an issue.

The problem - which involves ordering of data returned by a database query - wasn't revealed earlier as the unit tests covering this area didn't use enough, varied, test data.

I'll update this github issue as I make progress.

I appreciate your feedback and apologise for the hassle it caused you.

**Comment by jameshnsears** [comment]
I've investigated some more and the issue I discovered yesterday is more of a non issue. It only effects the expectation in a unit test involving sequential order - and it's debatable how the expectation ordering should be.

What this means is that at the moment, I can't repeat your problem. For example, say I visit the Author "Adam Smith", who has 6 quotations:

If I press the "Next, sequential" button I get the following, first word, order:
1. Man
2. Labour
3. The
4. It
5. People
6. There

If I then press the "First, clears Previous" button and then the  "Next, random" button 5 times I don't get this order. I'll admit that some of the order might match the same sequence as when I press "Next, sequential" but that's just the nature of a small data set.

Can you elaborate on your issue a bit more and give me a specific example of this identical behaviour?

**Comment by jameshnsears** [comment]
I'm going to close this issue, as I can't reproduce it. But if you get back to me with more details - maybe even a screen recording -  than I'll happily re-open this ticket.
