### ISSUE TITLE
Backup Option, Author's Name, Notification Only.

### ISSUE THREAD

**Issue by francisbegbie** [jameshnsears/QuoteUnquote#13]
Thanks for the wonderful app.

1. I use custom ROM and change my OS from time to time which requires me to reinstall all apps including 'Quote Unquote'.
I want to backup the app settings and the current state (eg. track the quotes that have already been displayed, so that they are not repeated with the next install ). I know there is a feature to sync between devices, but that would not work in my case.

2. While sharing the quote, I want the app to include the author's name.

3. Under Schedule / Display, add 'Notification Only' option.

If you need any information or clarity, let me know.

**Comment by jameshnsears** [comment]
Hi - thank you for raising these issues.

I had thought about implementing 1 previously - just no one asked for it till now. You have motivated me! I'll implement it.

I'm surprised about 2 - Share used to include the authors name, at least on the devices I used to use. However, I can see it's not working on the Android 12 device closest at hand. I'll definitely fix this, as it's something that definitely should exist.

Issue 3 is interesting - as it kind of put's the database ahead of what's displayed on the relevant widget. However, I'll look into this as I don't see why that isn't a problem, especially because it's something I never thought of :-)

I'll start working on this three issues. You can track progress of this issue in https://github.com/jameshnsears/QuoteUnquote/projects/1 (as well as in the source code).

Once again, thank you for bringing these things to my attention.

**Comment by francisbegbie** [comment]
Glad you liked the suggestions and decided to include them. Looking forward to the next iteration.

**Comment by jameshnsears** [comment]
Hi - here's an update...

Issue 3:
I've investigated and this request raises some questions concerning what I call the "viewed count".

For example, I'm currently viewing "Johann Wolfgang von Goethe" whom has 234 quotations. Currently I have a "viewed count" of 66/234 shown in a widget. If I had a "Notification only" - on, say, a recurring time - then what happens to the displayed "viewed count"?

At present a recurring time event will change the "viewed count" to 67/234 - which is consistent and easy to understand, especially as the total count, of 234, stays constant whenever you use the app for this author.

Can you clarify how you might expect a "Notification only" might affect the "viewed count"?

Issue 2:
I've released a fix for this issue; it will likely take a few days to become available in F-Droid, less for Google Play.

Issue 1:
I'll commence work on this next and, assuming no issues, it Will likely follow in the subsequent release.

**Comment by francisbegbie** [comment]
Hi,

I don't think I _fully_ understand your concerns regarding 'viewed count'. 

In my opinion, 'viewed count' should behave the same way as it does in the widget. 

That is, after a time event, the quotation should change (random or serial order) and so should the 'viewed count' of the author / overall.

By 'Notification Only' option, I was expecting a 'dismissable' or persistent notification (depending on user choice) with the quote, author's name, 'viewed count' and some buttons (favourite, next, dismiss, snooze, etc) at the bottom.

Eg: 

Persistent notification - The quote and 'viewed count' changes after the time event.

Dismissable notification - If the notification is dismissed, then a new notification (with new quote) appears after the time event and 'viewed count' is incremented by 1.

If the notification is snoozed, then a new notification (with same quote) appears after the said interval. No change in the 'viewed count'.

If user presses 'next', a new quote is displayed and 'viewed count' is once again incremented by 1.

Thanks.

**Comment by jameshnsears** [comment]
OK - thanks for that. It's cleared things up in my mind; such that the "viewed count" issue I was thinking about isn't applicable.

So, thank you for providing clarification.

I'll revisit this Notification issue after I've completed & released a backup / restore feature (which I'll work on now).

**Comment by francisbegbie** [comment]
Author's name while sharing quote.

_Issue 2:
I've released a fix for this issue; it will likely take a few days to become available in F-Droid, less for Google Play._

I can confirm that the above issue has been resolved.

**Comment by jameshnsears** [comment]
Hi - thanks for the confirmation about author name sharing.

I've released a new version of the App that includes a Backup & Restore feature (see screenshot). It should be available within a few days in Google Play & F-Droid. This feature was something that needed to be implemented so I'm glad you mentioned it. When it appears, let me know if you spot a problem.

I'll start investigating the Notification improvement suggestion next & will update this issue when I've implemented something / have more questions.

![Screenshot_1652277312](https://user-images.githubusercontent.com/828019/167867208-17f1bcdb-2343-4cfe-8a50-f0b0ea93804e.png)

**Comment by francisbegbie** [comment]
Hi,

Thanks for the update. 

I've been waiting for the new version to drop on F-Droid. Been 5 days. No luck as of now. 

Regards
Robin.

**Comment by francisbegbie** [comment]
Another feature request:

Is it possible to have an indicator for the most current quote? An asterisk or some other icon.

I've set the widget to change on a daily basis. Sometimes I like to review the last 10-15 quotes using the back button. When I go back (using forward button), I forget the latest one and invariably 'view' an extra one before realizing my folly.  

Regards

**Comment by jameshnsears** [comment]
I've noticed it not being published in F-Droid as well. Sometimes F-Droid can be a bit slow (as can Google) to publish.

It's possible to download https://f-droid.org/packages/de.storchp.fdroidbuildstatus/ and search for "Quote Unquote" and see that the version of the app containing the Backup / Restore feature has been successfully built by F-Droid. If the app passes their build process then - I suspect - it's very unlikely to be a fault of the app that's causing the delay. Most likely their build process is busy and I probably published to them at a less than ideal time, in respect of the build cycle.

Saying that, if it hasn't appeared a a couple of days I'll raise an issue in one of their forums.

I'll look into that idea about an indicator for the most current quote.  I'm actually having to think something along those lines for a part of the improved Notification functionality, so your suggestion is timely (and appreciated).

**Comment by francisbegbie** [comment]
Hi,

The latest version finally arrived on F-droid. 

A) Bug:

I had viewed 53 quotes until today. However, post restoration, the widget displayed only 52 quotes. 

The order went something like this when I pressed the _back_ button:

53,52,51,50 .... 46,45,44,_1_,42,41,40 .... 5,4,3,2,1, then 42,41,40 .... 5,4,3,2,1,42,41,40 and so on in a loop.

Note: 
43 is missing and is replaced by 1.
After reaching 1, it should restart from 53 and not 42.

Clicking _forward_ button at 42 brought 1 followed by 43,44,45 and so on.

Let me know if you want my 'token' for investigating the matter.

Favourites and settings were captured correctly.

I have now downloaded the Google Play version of your app. F-droid took way too long  :-)

B) Observation:

Do you think there should be an option to backup and restore locally? Personally I have no problem with the cloud but some would have issues over privacy.

**Comment by jameshnsears** [comment]
Hi - thanks for persevering with this. I appreciate it.

Please provide the token and I'll take a look. I'll likely include your tokens data as a unit test, but in the meantime I'll look into this ordering in the existing unit tests that I wrote.

That data that's backed-up includes the order the data was originally placed into the database. It might be that the code isn't working / being tested as this ordering scenario requires.

I agree, F-Droid can be a bit slow. But, it does get there in the end (as I noticed the update last night as well).

I'll likely implement this Backup & Restore with an option similar to exporting the favourites - i.e. to the file systemm. As I agree with you that some people would prefer to avoid such a cloud like solution.

**Comment by francisbegbie** [comment]
Token - cG9qH4OF9a

**Comment by jameshnsears** [comment]
Thanks. It's a problem with the new restore code (the backup data is good; just the restore isn't). I'll update this ticket when I have deployed a fix.

**Comment by jameshnsears** [comment]
Hi - I've just pushed to Google's Play Store version 3.0.1. It should fix the issue you spotted (I've improved my unit tests and tested manually), but let me know if otherwise.

I've also let F-Droid know of 3.0.1 - expect between 3 and 5 days for that to show up.

I'll move back to the Notification issue now.

Thanks for raising, and perceiving with, this Backup / Restore feature, it's certainly handy.

PS - I'll implement a file solution after the Notification work.

**Comment by francisbegbie** [comment]
Hi,

I can confirm that post restoration the latest version (3.0.1) is displaying quotes in the correct order. Backup/Restore option makes it so much easier to switch ROMs or phones without having to start afresh.

When I pressed back button after reaching 1, it did not take me to the latest quote. I had to press forward button multiple times. Depending on how many quotes have been seen, this could be any number -  50, 100, 200, etc. Hope you see the value in having a 'jump' button. It can have the same icon as the 'latest quote indicator' suggested earlier.

I was wondering why there is no 'save/apply' button on the configurations screen. Sometimes I forget the back gesture to lock the changes. (Not a feature request)

At the moment, the app includes 20,000+ quotes from 600+ authors. Are quotes repeated at any time - say when I switch from Authors (having viewed all quotes of one author) to All? If I select 'Favourites' (25 quotes), does it go around like a carousel or stop after reaching the last one? Curious to learn the logic.

Both the new 'edit' icon in the widget and updated instructions are quite handy additions. 

I started with 3 feature requests - it is now 6-7. Backup/Restore was the most important. I am glad that you added that feature. Other enhancements can wait. 

You've been most helpful. Thanks.

**Comment by jameshnsears** [comment]
Hi - thanks for the confirmation. 

I'll make a note of this "Jump button" idea (I store such idea's in a Trello board). I normally use the "Next, random" button to accomplish this jump - though I'll admit it does take you to the next random! For me the "Next, sequential" is more useful for things like Shakespeare, where order is most important.

No Save / Apply button? Well, for better or for worse, the App follows Google guidelines for building a widget with a configuration screen. In hindsight, I think I'd not follow all their recommendations.

Each of the quotation types - All; Author; Favourite; Search - have their own Previous records. If you have selected to store the displayed quotation in the All Previous, then for All you will never see the quotation again in moving through All. If you move to a different Author (or Search) then the Author Previous is reset, so going back to a prior Author will repeat what you first saw for that Author. 

Just so we don't loose track I'll release updates in the following order:
1. Improved notification: this will include "Favourite, toggle" and a selected "Next, ..." action buttons. The snooze feature will be the one that is baked into Android (so might / might not be available depending on version of Android).
2. A "Last Previous" indicator - to help tell you when your going to see a new quotation. 
3. A way to backup / restore the app from the file system.

I'll update this ticket when I release something (hopefully within the next week or so).

**Comment by jameshnsears** [comment]
I've just released 3.0.2 - same time frames apply as previously mentioned.

It includes improved Notification support & the "Last Previous" indicator.

Please let me know if you spot a problem!

I'll take a look into file system backup / restore next. Though will be little slower completing it.

**Comment by francisbegbie** [comment]
Hi,

'Last Previous' indicator (last seen quote) works as it should. Maybe you could move the icon slightly to the left (3-4 pixels) to make it stand out.

I was expecting a third option (separate one) for 'Notification'. Real estate on a phone screen is a precious commodity and is already populated with clock, weather widgets and at least one row of apps. Therefore I suggested a 'notification only' option. 

Trying to work around the available option (widget + notification) doesn't help as the notification disappears the moment I get rid of the widget. I understand that there could be technical reasons why my suggestion cannot be implemented. It is completely fine with me.

In order to test the latest version, I had to change the recurring option from time event (daily) to 'screen lock'. It did not work initially, I had to manually click the next button once and then lock / unlock the phone. Afterwards, it worked normally. Occasionally, the back button gesture (to lock) would not register. I will test it further and let you know.

No problem with 'Favourite, toggle' and 'Next, random' options in the notification. Assuming 'Next, random' changes to 'Next, sequential' depending on the chosen option.

Take your time with the file system backup / restore feature. 

Thanks.

**Comment by jameshnsears** [comment]
Hi - I'll adjust the 'Last Previous' indicator position in the next release (file system backup / restore).

> I understand that there could be technical reasons why my suggestion cannot be implemented. It is completely fine with me.

Try moving the widget to a different home screen? I normally drag / place my widget(s) onto a second, right hand side, home screen. At the moment though I think that's all I can suggest. I'll investigate some more, but I think we're in the realm of technical limitations of Android widgets.

> In order to test the latest version, I had to change the recurring option from time event (daily) to 'screen lock'. It did not work initially, I had to manually click the next button once and then lock / unlock the phone.

I'll investigate that as well, thanks for mentioning all these things by the way. You've helped improve the app, which is great.

I'll update this issue, when I have another release.

**Comment by jameshnsears** [comment]
Hi - no need to reply, but I've released 3.0.3:
- Fix: Power on / off detection.
- Improve: Slightly reposition Last Previous indicator.

Expect 3.0.4 to take longer ;-)

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jump Button - When I pressed back button after reaching 1, it did not take me to the latest quote. I had to press forward button multiple times. Depending on how many quotes have been seen, this could be any number - 50, 100, 200, etc. Hope you see the value in having a 'jump' button. It can have the same icon as the 'latest quote indicator' suggested earlier.](https://trello.com/c/GnCdF5HP/1777-jump-button-when-i-pressed-back-button-after-reaching-1-it-did-not-take-me-to-the-latest-quote-i-had-to-press-forward-button-mul)

**Comment by francisbegbie** [comment]
Hi,

Instead of slowing down, you're on overdrive!

Thanks for the following changes:

1. Offline storage.
2. Repositioning of indicator.
3. Improved detection (change event).

Looking forward to the final one - Jump button.

**Comment by jameshnsears** [comment]
Hi - thanks for all your feedback. It makes that App better which is great.

I'm going to close this ticket now, as version 3.0.5 - which I'm about to release - contains the Jump button.

If you spot any issues / have more suggestions please raise a new Issue :-)

**Comment by francisbegbie** [comment]
Thanks for explaining the logic. I will now keep mum and let you work on
the next iteration.
