### ISSUE TITLE
edit quote data base

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#14]
1 Many people want quotes for a specific subject or goal it would be nice if the quote data base could be edited so that it only held the quotes the user wanted and the user could add their own quotes

Maybe have a custom quotes added from a csv text file. Maybe have an option to only show the custom text file quotes

2 if there is a custom quote database it would be nice if there was on device backup. No everyone wants to put things in the cloud when a 5tb drive is under $100

**Comment by jameshnsears** [comment]
Hi - thanks for raising this issue (and the others, which I'll answer individually, after this one).

1. I'll look into this option, it sounds like a good idea. What particular format do you think the data should take? Something as "open" as possible, so anyone could create the file might be best? Something like JSON, to me, sounds less "open", then something like a .csv file. What do you think?

2. The next version, 3.0.4, includes a "Shared storage" (which includes on device) option on the Archive tab; so point 2 is coded and will be released next.

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Import a CSV](https://trello.com/c/V2jaJyIM/1824-import-a-csv)

**Comment by nutpantz** [comment]
I'm all for something simple like csv, just about anyone can edit a text file.
But whatever is the best for you.
Worse case would be a tutorial on how to edit the database you use now, and a method to switch from the internal database to a custom one.

**Comment by jameshnsears** [comment]
Hi - I've released version 4.0.0, it includes the ability to import a .csv of quotations.

The release should appear in Google Play / F-droid within a few days.

If you spot a problem, or think things need improving, please let me know via a new GitHub issue.

Thanks.
