### ISSUE TITLE
Black widget back ground

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#15]
I could not find a dark widget background.
It would be nice if there was black, dark grey and dark versions of other colors. It a custom color picker. 
I like dark colors because the use battery

**Comment by jameshnsears** [comment]
A custom colour picker sounds like the best approach, I'll investigate, and see how it compares with what exists currently...

There is a dark background, black, in the Appearance tab > Background colour. I use it all the time :-) 

I admit it's hard to see in the list of colours, so maybe that points all the better to a colour picker!

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colour Picker](https://trello.com/c/JieYI5Dd/1821-colour-picker)

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colour Picker](https://trello.com/c/JieYI5Dd/1821-colour-picker)

**Comment by jameshnsears** [comment]
OK - I'm closing this issue, as I released 3.0.6 (it should take a few days to appear in a Play Store / F-Droid).

3.0.6 includes colour choosers for background / text / buttons.

If you hit a problem please raise another issue + thanks for raising this issue in the first place :-)
