### ISSUE TITLE
toolbar joined widget

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#16]
It would be nice if the small space between the tool bar and widget was gone as an option.

**Comment by jameshnsears** [comment]
That's a good idea, and sounds doable. I'll implement it - most likely much sooner than your other suggestions as it, at the moment, sounds easiest :-)

Thanks for raising all these issues individually & you can track them on https://github.com/jameshnsears/QuoteUnquote/projects/1

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New, unified, layout for widget](https://trello.com/c/ydpcbTGV/1823-new-unified-layout-for-widget)

**Comment by jameshnsears** [comment]
Hi - I'm closing this issue as the functionality is now inside version 3.0.5

Thanks for coming up with this suggestion :-)
