### ISSUE TITLE
tap widget to change quote

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#17]
It would be nice if you could just tap the widget to change the quote. Get rid of the tool bar all together and tap the widget to do things. Have a setting for options like advanced next or advanced random. Maybe even double tap for favorite or other options.
Or maybe tap left side for advance random right side for next and middle for favorite.

**Comment by jameshnsears** [comment]
Hi - the left / right button idea isn't viable as they take up too much space inside the widget. I tried it many moons ago.

It would be possible to implement some sort of double tap, or triple tap if need be - but I think this approach is too different from how other things work in Android. That's to say, it's pretty much one tap for everything. Where as this approach requires at least three taps - i.e. next; favourite; configure

You're welcome to submit a PR with an implementation, but for the moment (unless more people raise a similar request as this one) then this isn't something I'm going to implement.

**Comment by Nikoichu** [comment]
+1 for this.
Another way to implement it would be with swipe gestures. I've seen it done in another app (habits, it's also open source) - swipe right for next quote and left for previous, double tap for favorite (in line with a certain social media). I think this issue could use some reconsidering.

**Comment by jameshnsears** [comment]
Hi - please provide a link to this "habits" app. I'll take a look at it and reconsider my previous opinion :-)

**Comment by Nikoichu** [comment]
@jameshnsears https://github.com/iSoron/uhabits
Hers it is. Huh, it seems it isn't called just "habits" lol.
Basically when you create a widget, you can select multiple habits for that widget and you can switch between them with swipe gestures.

**Comment by jameshnsears** [comment]
OK - I've researched into better gesture support and this is what I've found.

First off, Android restricts what gestures are available to App Widgets (that reside on a home screen) - meaning the following gestures are not available:
- double tap
- long press
- left and right swiping

All that's applicable, to Quote Unquote, is single tap; and vertical scrolling or vertical swiping.

Quote Unquote uses single tap and vertical scrolling.

The Habits / uhabits app (and some Photo Gallery App Widgets) uses single tap and vertical swiping.

Quote Unquote does not use vertical swiping as what you swipe is not text but an image. An image does not "work" for Quote Unquote as you need scrolling to be able to read all of the quotation.

I do appreciate this issue being raised but am closing it as there is no way to do what has been requested.
