### ISSUE TITLE
Rounded widget edges

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#18]
The sharp corners of the background look a little jarring, maybe add an option to round them?

**Comment by jameshnsears** [comment]
Android 12 changes the look of widgets - it gives them rounded corners. So, on 12, Quote Unquote has rounded corners.

I did look into this a while ago (pre Android 12), and the outcome looked more jarring than right angles.

I'll leave this ticket open and revisit this issue after version 3.0.6 is released. If I can implement it satisfactorily then I'll do this in release 3.0.7. Either way I'll update this issue in the future.

**Comment by jameshnsears** [comment]
Hi - I have investigated. 

It's possible in earlier versions of Android to have rounded corners on a widget, But for this widget it's not possible (as far as I can find out). 

This widget allows a wide range of background colour / transparency permutations - especially with the upcoming colour chooser code in the next release. Corners need to be defined beforehand with a specific colour. There is no way to define the corners beforehand in a way that supports all the colour / transparency permutations.

Hence I am closing this issue.

Thanks for raising this issue though :-)
