### ISSUE TITLE
Make color of toolbar buttons the same as text color

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#19]
The buttons being black, when the text is white makes no sense at all, they should be the same for consistency's sake. Or even make a separate color selector for the buttons.

**Comment by jameshnsears** [comment]
Hi - you are right! The next version 3.0.6 - which I'm currently working on - includes colour choosers for all colours.

I'll close this issue when I've deployed.

**Comment by jameshnsears** [comment]
OK - I'm closing this issue, as I released 3.0.6 (it should take a few days to appear in a Play Store / F-Droid).

3.0.6 includes colour choosers for background / text / buttons.

If you hit a problem please raise another issue + thanks for raising this issue in the first place :-)
