### ISSUE TITLE
A way to export favorites?

### ISSUE THREAD

**Issue by AbstractGeek** [jameshnsears/QuoteUnquote#2]
Thanks for fun app, I enjoy browsing through quotes and this is app is apt for it 😄 

I was wondering if there was a way to export favorites?

**Comment by jameshnsears** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Export favourites?](https://trello.com/c/tWfgQANk/1254-export-favourites)

**Comment by AbstractGeek** [comment]
I didn't know the favorites sync between devices, pretty cool! But yeah that is not what I mean.

I meant something basic like a text file export - all the favorites are pooled into a text file and exported on device storage. This would enable me to review my favorites on my computer and copy the ones I really like elsewhere.

**Comment by jameshnsears** [comment]
Hi Dinesh - Thanks for explanation. I'll start coding this feature. Don't hold your breath though: it takes a while for me to code new features!

You can track "progress" on: https://github.com/jameshnsears/QuoteUnquote/projects/1 & in any notifications on this issue.

**Comment by jameshnsears** [comment]
App now has an Export feature, to local / remote storage. Software released; but might take a few days to appear in Google Play.

If you have any other suggestions / spot problems please raise another GitHub issue.
