### ISSUE TITLE
Select different font style for the author

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#22]
A purely aesthetic consideration, but quotes are usually displayed in italic, with the authors in normal font, or vice versa, it would be nice to be able to mimic this style.
Just add a separate font option for the author text.

**Comment by jameshnsears** [comment]
That sounds like a very good idea. Thank you for suggesting it! 

I'll see what I can do for version 3.0.7

**Comment by jameshnsears** [comment]
Hi - I have released 3.0.7 - which contains a solution to this issue.

It will take a few days for it to appear in Google Play & F-Droid.

Let me know if you spot a problem and I'll re-open this issue.
