### ISSUE TITLE
option to hide author 

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#23]
I'm 99 %  interested in the quote then the author so it would be nice if showing the author name was optional. Maybe have a temporary unhide when i am temporary curious about the authors name.
Maybe custom font or size for author only might be interesting.

**Comment by jameshnsears** [comment]
Hi - I have released 3.0.7 - which contains a solution to this issue.

It will take a few days for it to appear in Google Play & F-Droid.

Let me know if you spot a problem and I'll re-open this issue.
