### ISSUE TITLE
Option "Next, random" advances sequentially daily

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#24]
Version: 3.0.4 FDroid
Android 10
Lawnchair Launcher (version 1.2.1.2001 from FDroid)

I have set the option "next, random" under the "Notifictions" options, but it only goes up one quote sequentially each day.

I don't know if I'm misunderstanding the option, but I thought it would jump to a random quote each day.

![Screenshot_20220605-100759_Quote_Unquote](https://user-images.githubusercontent.com/42444745/172039689-8f60107d-443f-4e78-a6ac-bdc8243500ae.png)

Here is a screenshot of my options, if it helps.

**Comment by jameshnsears** [comment]
Hi - I can't repeat this behaviour.

Can you try this with a small set of quotations - i.e. A. A. Milne - and record a brief video?

The random feature should display a random quotation, from those you have not seen, from the content you have selected.

**Comment by Nikoichu** [comment]
I enabled the toolbar button for "next, random" and clicking it, it still only goes one up sequentially, like if I'm at quote 5/20568, it goes up to 6/20568. Is this the intended behaviour? Is it displaying how many quotes I've read, while being actually randomized?

Btw how do I post a video on here?

**Comment by jameshnsears** [comment]
Hi - the App is working as intended. I'll explain how it works:

Say you select an author - A. A. Milne - who has 5 quotations.

If I press the "Next, sequential" button (4 times) then I get to see the following Quotations (I'll show first word only):
I; One; Weeds; Time; To

This is the order that the quotations were inserted into the database.

If I press the "First, clears Previous" button and then press the "Next, random" button (4 times) I get (this time):
I; Weeds; To; One; Time

Each press of the "Next, random" will give you a random quotation (that you have not previously seen) from the Quotations you selected.

The first counter shows how many previous quotations you have seen (by pressing either Next button), the second counter how many Quotations are available.

I'll close this issue, as the App is working as intended. But if you have any more questions please raise them. it's not a problem :-)

**Comment by Nikoichu** [comment]
I see, my bad then, I got mislead by the counter. Thanks for the answer and the awesome app! ❤️
