### ISSUE TITLE
TTS: Read aloud

### ISSUE THREAD

**Issue by Pantyhose-X** [jameshnsears/QuoteUnquote#246]
Play button
  Use the system built-in TTS

**Comment by jameshnsears** [comment]
Hi (again). I never thought of implementing this, so thanks for the suggestion. Can you clarify how a user might use such a feature?

**Comment by Pantyhose-X** [comment]
Steps
1. When Celebrity Quotes Timing Auto Change,
2.TTS automatic pronunciation, and Click on Play button pronunciation

**Comment by jameshnsears** [comment]
Initial release will be TTS option on notification only.

**Comment by jameshnsears** [comment]
Released, at least a first version. Let me know if you have problems & thanks for the idea.
