### ISSUE TITLE
random advance just goes to the last quote

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#25]
On latest fdroid 306.
I picked one author che 
Using the random advance just goes to the last quote of the author #17 
Forward and back work fine but from where ever i am when i hit random advance it goes to#17 of che.
After i switched to a different author random now only advances forward one quote. I'll do some more testing and report back

**Comment by nutpantz** [comment]
Ok after some more testing. On a fresh install, with a specific author .It looks like random advance is just going to the next unseen quote and when it gets to the last quote, it only goes to the last quote.

**Comment by jameshnsears** [comment]
Hi - thanks for raising this issue. 

The app is working as intended. When it runs out of "Next" quotations it just shows you the last one.
