### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by saralam13** [jameshnsears/QuoteUnquote#261]
Recurring an event does not work, I check the box, but it is not saved

**Comment by jameshnsears** [comment]
Hi - sorry for the delay in answering + thanks for raising the issue.

Which version of Android are you using? And can you let me know the version of the app (bottom left on the Instructions page).

If your able to upload a short video of what your experiencing then even better.

I've tried repeating your situation but so far am not able.

**Comment by saralam13** [comment]
Hi, I am using android version 11. The application version is 4.37.0

**Comment by jameshnsears** [comment]
Thanks - I can repeat this on Android 11. I'll code a fix and update this issue as I make process.

Thanks for reporting this!

**Comment by jameshnsears** [comment]
Hi - I've just published a new version of the app: 4.38.0

It might take a few days to be published by Google Play / F-droid. 

Hopefully it will fix your issue. Please let me know if it does not.

Once again, thanks for reporting this issue. I appreciate it!

PS - I'll leave this issue open for a few days just in case anything crops up.

**Comment by saralam13** [comment]
Unfortunately, the problem has not disappeared. And I updated to the latest version. In this case, I'll explain the problem in more detail in the widget settings on the third tab of the Notifications. In the Recurring Events section, only the Screen lock item retains its value. The two lower items do not retain their value.

**Comment by jameshnsears** [comment]
Hi - thanks for the follow up.

I could reproduce your issue in version 4.37.0 but I can't in 4.38.0.

Have you tried restarting your device? Sometimes this helps clean up any caching issues in older versions of Android.

If a restart doesn't work then can you uninstall the app and download and install the app (in .apk form) from https://github.com/jameshnsears/QuoteUnquote/releases/tag/4.38.0-fdroid

You might need to allow your browser / device to install apps from an unknown source!

This .apk is only different from the Google Play version in that it doesn't contain any auditing.

Let me know if either of these things fixes things.

Can you also let me know what device manufacturer and model you're using?

Thanks.

**Comment by saralam13** [comment]
Thank you, your recommendations helped.
