### ISSUE TITLE
feature req: hide source info in display

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#266]
i don't need to see the source. Or the quote #

I would like to remove that line, have an option at least

**Comment by jameshnsears** [comment]
Hi - in the Configuration > Appearance > Style > Text area you should be able to click on the Source and Position buttons, both have a Hide switch. 

Does that fix your issue?

**Comment by nutpantz** [comment]
Yes.
I never knew those buttons were anything but decorations. 
Thanks
