### ISSUE TITLE
Create your own quote.

### ISSUE THREAD

**Issue by KAGEYAM4** [jameshnsears/QuoteUnquote#27]
Sometimes i find quotes which relates to me and what i wannna be doing. So custom support where you can manually add quotes and display all custom created quotes. Thank you

**Comment by jameshnsears** [comment]
Hi - thanks for raising this issue.

I am currently working on version 4.0.0 - this will feature the ability to load a .csv file which will allow you to load whatever quotes you like.

I'll keep this issue open until 4.0.0 is released and then we can revisit this issue to see if it satisfies your feature request.

If you have any questions please update this issue.

**Comment by jameshnsears** [comment]
Hi - I've released version 4.0.0, it includes the ability to import a .csv of "custom quotes".

The release should appear in Google Play / F-droid within a few days.

If you spot a problem, or think things need improving to better match your requirements, please let me know via a new GitHub issue.

Thanks.
