### ISSUE TITLE
Recycling of imported source does not work

### ISSUE THREAD

**Issue by tneddermann** [jameshnsears/QuoteUnquote#275]
I installed 4.38.0 from F-Droid, created my own small list of affirmations (31 entries), configured the app to show also notifications and set up a schedule of every 2 hours.
When the last affirmation is reached it seems that the app does not recycle (as it is documented in this [issue](https://github.com/jameshnsears/QuoteUnquote/issues/133) and shows the last entry every 2 hours.

I would be glad to provide a detailed log to solve the issue but I do not know how I can create one.

Many thanks for your work on this helpful app!

**Comment by jameshnsears** [comment]
Hi - Thanks for raising this & apologies for not getting back to you sooner.

Can you send me some screenshots from the configuration screen? Ideally for the Filter / Database / Toolbar tabs.

I'll get back to you (in a speedier manner) when I get these screenshots.

If taking screenshots is a problem, let me know in this issue.

**Comment by tneddermann** [comment]
Hi,

many thanks for your feedback.

I feel a bit stupid, since I found my mistake during taking the screenshots. In the "Notifications" - "Action" tab I had selected "next, sequential". 🫣
Since I did not care whether the affirmations are shown in the CSV order or random, I did not change this setting. It did not came to my mind, that the app would not recycle then.
But the behaviour of the app in this config together with a regular schedule and a small amount of database entries does not make much sense, because the app gets useless when the last entry is reached.

So the initial issue can (likely) be closed but can act as a hint for a possible improvement.

Anyhow, here my screenshots for reference:

![Screenshot_20240513-172335~2.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/00e0a28d-22db-42b7-90d9-77205b0cf633)

![Screenshot_20240513-175153~3.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/1efa3a13-fbc2-4212-b8d5-416af8118ade)

![Screenshot_20240513-175214~2.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/5542b011-fba3-407c-ac62-146e521f7d57)

![Screenshot_20240513-175324~2.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/78c0e88f-4c8a-4411-ae7a-310e1b5507e5)

![Screenshot_20240513-175336~2.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/c4c5f422-4e59-45e7-bad7-29bf3f71aa51)

And how it seems to work ( I will keep an eye on it, in the next days):

![Screenshot_20240513-175422~2.png](https://github.com/jameshnsears/QuoteUnquote/assets/83392071/0023e1ee-d7b7-4c03-ac7d-c4758f3c54f0)

**Comment by jameshnsears** [comment]
Hi - no problem at all with you raising this issue. I'm glad you did in fact.

There are some minor updates to the app that I have been thinking about - so in the next release I'll include recycling on the sequential action.

I won't close this issue until I've releases the change - so you'll have some visibility.

**Comment by jameshnsears** [comment]
Hi - I'm closing this issue now. I just released a new version of the app - 4.39.0 - which includes recycling on both next random / sequential actions.

I'd just like to thank you for taking the time to raise this issue and for helping improve the app!

PS - it takes a few days for F-Droid to release a new version of any app.

**Comment by tneddermann** [comment]
Many thanks for your fast fix.

With the random config set, this morning the app successfully jumped from showing entry 31/31 to 1/31. So this option already fixed my problem but I will check the other option again, when the release has been distributed by F-Droid.
