### ISSUE TITLE
Custom schedule and quiet times

### ISSUE THREAD

**Issue by tneddermann** [jameshnsears/QuoteUnquote#276]
The app allows to show the next quote at unlocking, every 2 hours starting at midnight or at a configurable time of the day.

Is it possible to enhance the feature of the regular interval to a customizable interval (e.g. every 4h starting from 6:30)?

Additionally an option of configurable quiet hours (like no new notifications between e.g. 22:00 and 6:00) would be ideal. Android's "Do not disturb" mode (configurable for the night) suppresses the pop up of notifications but they are all shown when the mode is switched off.

Many thanks.

**Comment by jameshnsears** [comment]
Hi - these sound like good ideas. Thank you for taking the time to suggest them. I really do appreciate it.

I wasn't planing on doing any significant work on this app until around the end of summer (bar fixing any defects - of which, at the moment, I'm not sure issue #275 is).

Let me see how #275 resolves before I make a commitment as to when I could start this feature request. Though I will implement this feature.

**Comment by jameshnsears** [comment]
Hi - I've published 4.40.0: it contains an initial solution for this issue. Let me know if you spot a problem, or if my solution differs too much from your expectation!

PS - It normally takes a few days to get picked up and released by F-Droid.

**Comment by tneddermann** [comment]
Sorry for the late feedback.
I became a father again and had other priorities. 😉

Your solution is absolutely fine for me. Many thanks. I did not expect that you would implement the proposal so quickly.
Actually I had three input fields for start, end and interval in mind, so that the notifications could be shown also at half hour, etc. but I'm already very happy with your implementation. Now I'm reminded from 7am to 9pm every three  hours with some positive sentences.

In the Android system settings I furthermore configured a custom sound for the notifications (a Tibetan bell). By this your app gives me exactly what I need.

Is there a way to support your work with a small  amount?

**Comment by jameshnsears** [comment]
No problem recieving your "late" reply. Though I think congratulations from
me to you should come first.

It's very kind of you to offer something, but, if truth be told, I'd feel
like a bit of a fraud recieving anything. The quotes aren't mine and most
of the best ideas come from users. Also, I secretly worry about any - so
far unknown - defects.

Saying that, I'd happily receive your Tibetan bell sound :-)

Thank you for such a nice email.

**Comment by tneddermann** [comment]
Before I stumbled upon QuoteUnquote I tried to use [mindfulnotifier](https://github.com/kmac/mindfulnotifier) which did not work for me.

In the description of this app links to several  bell sounds are given:

> Bells
> Bell 1: is from user 'steaq' via https://freesound.org/s/346328 and is licensed under the Creative Commons 0 License.

> Bell 2: is from user 'itsallhappening' via https://freesound.org/people/itsallhappening/sounds/48795 and is licensed under the Creative Commons Sampling+ License

> Bell 3: is from user 'suburban grilla' via https://freesound.org/people/suburban%20grilla/sounds/2166 and is licensed under the Creative Commons Sampling+ License

> Bell 4: is from user 'kerri' via https://freesound.org/people/kerri/sounds/27421/ and is licensed under the Creative Commons Attribution License

> Bell 5: is from user 'dobroide' via https://freesound.org/people/dobroide/sounds/436976/ and is licensed under the Creative Commons Attribution License

I think I used bell 2 and since I do not own the rights, I just give the reference to the files here.

Many thanks for your work!
