### ISSUE TITLE
Updated ru (Russian) translation

### ISSUE THREAD

**Issue by chel1k** [jameshnsears/QuoteUnquote#28]
I have translated your application into `ru` (*Russian*). Here is the xml:
https://hastebin.com/tetotiquho

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by jameshnsears** [comment]
Thank you. I'll review this once I have completed release 4.0.0 - which I am currently working on.

**Comment by jameshnsears** [comment]
Hi - sorry for not getting back earlier, but version 4.0.0 is almost ready for release.

4.0.0 has a different strings.xml - I've attached it.

 If you still interested in a RU translation then please update this issue with the new strings.xml

[strings.xml.tar.gz](https://github.com/jameshnsears/QuoteUnquote/files/9453951/strings.xml.tar.gz)

**Comment by chel1k** [comment]
https://hastebin.com/rujoyitapi

**Comment by jameshnsears** [comment]
Archive of https://hastebin.com/rujoyitapi 
[strings.xml.tar.gz](https://github.com/jameshnsears/QuoteUnquote/files/9461070/strings.xml.tar.gz)

**Comment by jameshnsears** [comment]
Hi - I've done a diff against what you supplied and the strings.xml in the code.

Some things are missing and some some things have not been translated.

Can you let me know which tool / site you used from the translation?

I want to check it out as the next release will need further translation as strings.xml is having something added to it.

PS - sorry to be a pain.
