### ISSUE TITLE
Option to fully remove/hide toolbar

### ISSUE THREAD

**Issue by skelletime** [jameshnsears/QuoteUnquote#287]
Please add an option to entirely remove the toolbar. You can remove all the icons, but there is still a gap at the bottom where the toolbar would go that makes the spacing within the widget uneven for short quotes & cuts off the text for longer quotes.

A convenient solution would be a "Hide" toggle like there is for the source & position, but I would be happy if the blank space just went away when all the icons are unchecked.

Edit: I went to take a screenshot of this and realized I got mixed up. I thought I was seeing text cut off for longer quotes earlier, but it was actually because I'd selected a dark BG color for the widget before I realized the toolbar existed, and I couldn't see the buttons. The "Hide" toggle may still be useful for some, but #289 handles my actual issue for my use case.

**Comment by jameshnsears** [comment]
Hi - sorry for not replying earlier as I was away on holiday & a laptop. I'll investigate this & get back to you.

**Comment by jameshnsears** [comment]
Closed as #289 duplicates it.
