### ISSUE TITLE
Sequential display in widget is random instead

### ISSUE THREAD

**Issue by skelletime** [jameshnsears/QuoteUnquote#288]
Gonna give some detail since I'm not sure if my config is right for my intended behavior. Here's what I did:

- Installed v.4.39 from F-Droid
- Created the widget & customized it
- Imported my own .csv of 5 quotes
- Checked the "Screen Unlock" option under "Recurring Event"
- "Action" is set to "Next, sequential"

When I unlock the screen, the quote changes, but it appears to be random rather than sequential. At first it seemed sequential til it got to the end, and then appeared to be going back and forth between the last two quotes after that. Then I realized it was probably just true random, and sure enough it's continued to jump randomly around the list since then.

I set the toggle to random, exited, and set it to sequential again to see if it made a difference. It didn't. Toolbar buttons do not have this issue.

![Screenshot_20240522-235611](https://github.com/jameshnsears/QuoteUnquote/assets/6140107/3f21946c-3712-44d2-91d1-27ae7f0ae12f)

![Screenshot_20240522-235645](https://github.com/jameshnsears/QuoteUnquote/assets/6140107/bffa31fd-f771-49a5-a22f-87bf7c82d762)

**Comment by skelletime** [comment]
Okay, so I switched DBs to get a screenshot of a longer quote for the toolbar issue. When I switched back to my custom DB, this issue disappeared. I don't know if maybe something needed to be re-initialized? But I can't replicate it anymore. Unsure if relevant, but I also noticed the app switched from "All" to "Source" on the quotations page by itself. Shouldn't make a difference, all my quotes have the same source.

Edit: No clue what changed but the behavior came back, it's random again. I didn't even open the config today. Happy to provide more details on request.

**Comment by jameshnsears** [comment]
Hi - 

1. I can't reproduce the original issue. If I load the following .csv file into the External database (and use All)...

a1||q1
a2||q2
b1||q3
b2||q4
b3||q5

... and use screen unlock to move next sequentially, then for me it works as expected. That's to say it goes from q1 to q5 and back to q1 and so on.

Switching to random works as intended as well.

If I alternative from random to sequential, or vice versa, then the behavior is as expected.

Try this out with my, above, .csv contents.

If your still seeing a problem, please provide me with your .csv (maybe even a short screen recording) and I'll investigate a bit more. But right now, I can't see a bug in the app.

2. The behavior you've described when switching between Internal and External can be improved with respect to remembering the prior database Filter info, I'll admit. I'll investigate that as part of this ticket.

**Comment by jameshnsears** [comment]
The next release will include an improvement when switching back and forth between databases. Otherwise I can't repeat the issue you described.
