### ISSUE TITLE
Vertical center align/option to adjust top padding

### ISSUE THREAD

**Issue by skelletime** [jameshnsears/QuoteUnquote#289]
Especially relevant for short quotes. Currently, even if I remove the toolbar, a single line of text is not centered vertically in the widget regardless of the widget size.

This could also be handled by giving an option to adjust space/padding at the top/before the quote, so it would be useful for longer quotes too.

![Screenshot_20240523-001346](https://github.com/jameshnsears/QuoteUnquote/assets/6140107/66b755b6-fe3e-49cb-bf58-66b1f160dfd5)

![Screenshot_20240523-004142](https://github.com/jameshnsears/QuoteUnquote/assets/6140107/eb64da72-f439-4c26-a38c-426701cef75d)

![Screenshot_20240523-004723](https://github.com/jameshnsears/QuoteUnquote/assets/6140107/994d95f7-73ca-4fe2-afc2-113df827c4f4)

P.S.: I really appreciate your work, QuoteUnquote is great! I've wanted something like this for years and finally found this app tonight.

**Comment by jameshnsears** [comment]
Hi - I'll investigate this & get back to you about it. Thanks for raising it (and the screenshots).

**Comment by jameshnsears** [comment]
Hi - a fix for this will be in the 4.40.0 release :-) Thanks for raising the issue. It's a small issue, but such things make a big difference.

I'll close this issue after I've released the app.

**Comment by jameshnsears** [comment]
Hi - 4.40.0 is published: it includes a fix for this issue. Let me know if my solution doesn't match your expectation!

PS - it can take a few days for F-Droid to publish this release (but Google Play is normally much faster).
