### ISSUE TITLE
Automatic backup

### ISSUE THREAD

**Issue by francisbegbie** [jameshnsears/QuoteUnquote#30]
I want backup (settings, favorites, past 'viewed quotes' history) to happen automatically (locally or cloud) at regular intervals (1,7,30 days).

**Comment by jameshnsears** [comment]
Hi - this sounds like a good idea. I'll implement it. Just don't hold your breath.

**Comment by francisbegbie** [comment]
Thanks, there is no hurry.

**Comment by jameshnsears** [comment]
Another person suggested the following: **do an auto backup to the cloud whenever an item is favorited**

**Comment by jameshnsears** [comment]
Well, it took a while but such an auto cloud backup feature is now published in 4.40.0

Thanks for raising the issue in the first place!

**Comment by francisbegbie** [comment]
Thanks for adding the feature. 
I understand auto local backup is also in the pipeline. #301
