### ISSUE TITLE
Blank widget, jump to current not working

### ISSUE THREAD

**Issue by francisbegbie** [jameshnsears/QuoteUnquote#32]
Version: 4.0.1-fdroid
Android: 11 (RQ3A.211001.001)

Apologies if the following is a little convoluted.

Today I updated the app from 4.0.0-fdroid to 4.0.1-fdroid without changing any settings. I am not sure if the problem started with version 4.0.0 or 4.0.1.

While fiddling with the back button (for previous quotes), I noticed that the widget turned blank (A) after showing the previous 5 quotes.

I had to press back button 10+ times to get another quote (B). The widget would then blank again and show the same quote (B) after a few tries - like a carousel. 

When I pressed the 'Jump to current' button, the widget did not display the current one. I had to click the button multiple times for that feature to work. 

Once back to the status quo (A), I pressed the forward button a few times (<10) hoping the previous 6 and current quote would show up in a cyclical order but they did not.

There was no change in the behaviour after rebooting the phone.

I thought maybe you removed some of the old quotes, so I cleared the app cache and restarted the phone once again. 

I noticed that the current quote (181 - Neil Patrick Harris) was not the same as before (I don't remember the exact number but it was quote regarding heaven, hell and soul). 

When I pressed the back button, it changed to 180,179,178,176 and stopped. Skipped 177. This time the 'Jumped to current' button worked. When I pressed forward button from 176, it skipped 177 and then went to 178 and so on.

I know version 4.0.2-fdroid is on the way but I don't think it has a fix for this problem.

I have two JSON files which I am unable to share here. One taken today with version 4.0.1-fdroid (uKainymXa4) and another one using version 3.2.1-fdroid ((filename suffixed with _1)) while filing issue #31 on 6th September 2022. The widget was then showing quote 165, so there is no way I would reach quote 181 within 4 days.

I have uploaded the latest JSON to Google Cloud. Hope that helps.

**Comment by jameshnsears** [comment]
Hi - I'm about to release 4.1.0 sometime today (hopefully), but it might take a few days to propagate to the stores.

4.1.0 should fix this issue (and add some related new functionality). I apologise for the hassle its caused you, and I certainly appreciate your, convoluted or not (it's not BTW), raising of this issue.

Essentially the history database is out of sync with the quotation database. 

Sometimes I release an updated quotations database, removing a quotation here and there that kind of seems "low quality". New External database functionality amplified this defect as I removed Sources that only contained one quotation, as the Source list just was too big to navigate.

The new 4.1.0 functionality and separate defect fix renders this removal obsolete, so I've reintroduced those Sources.

Before I release I'll take a look at uKainymXa4 and check things out. My expectation is that uKainymXa4 will work as expected with 4.1.0

I'll update this ticket prior to release.

**Comment by jameshnsears** [comment]
Hi - I've checked the restore of uKainymXa4 against 4.1.0 and I can traverse (previous and next) the All. I did Next on all the favourites and no problems there.

So, I've released 4.1.0.

I'll close this issue. But do let me know if you have any other problems (or ideas). And thank you for your time.
