### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by opk12** [jameshnsears/QuoteUnquote#320]
When importing a CSV file with this line, it would be convenient to have the line number in the toast error message.

    something||.

    invalid .csv format, line: empty quotation

**Comment by jameshnsears** [comment]
That's a good idea. I'll implement it in the next release!

Thanks for the suggestion :-)

**Comment by jameshnsears** [comment]
I've just released 4.43.0 - it includes showing a line # for when a CSV import fails.

Let me know if this is still an issue for you. And thanks for raising the issue, I appreciate it!

PS - release might take a day or so to show up due to review / build process in googleplay / fdroid
