### ISSUE TITLE
Add Text and button color option

### ISSUE THREAD

**Issue by KiritoStorm** [jameshnsears/QuoteUnquote#34]
It would be really nice to also set a color for text and the buttons.

I'm not sure if it makes sense to seperate it, but with a transparent effect on a dark background you can see nothing for example.

Thank you for this nice little app, keep going. 👍

**Comment by jameshnsears** [comment]
Hi - thanks for raising this issue (I really do appreciate it).

You should already be able to do this on the Appearance > Style / Toolbar page

Click on the the coloured bar to the right of the "Colour" text - it should raise a colour picker dialog.

You can do a similar thing for any of the three text fields: Quotation / Source / Position - if you press the appropriate button first.

Please let me know if this doesn't resolve this issue.

**Comment by KiritoStorm** [comment]
Alright, I haven't seen the toolbar tab, but there is no text color option right? :thinking:

**Comment by KiritoStorm** [comment]
Alright, it resolved my issue, thank you :+1:
