### ISSUE TITLE
Center quotes & source in same line

### ISSUE THREAD

**Issue by KiritoStorm** [jameshnsears/QuoteUnquote#35]
So quotes can be really long and short, so it would be nice to have the option to center the text, vertically and horizontally.
For me I would maybe do this as the default behavior.

Also it would also be nice then to have the option that the source is in the same line:
[Quote] - [Source]

**Comment by jameshnsears** [comment]
Hi - can you elaborate a bit more on this centering idea? Just so that its a bit clearer to me. A simple example would help.

A "compact view" with the quotation and source on the same line sounds possible (just so long that it preserves the link to wikipedia). I'll likely implement this in the future, after version 4.2.0 - as it reads like a good idea :-)

**Comment by KiritoStorm** [comment]
![image](https://user-images.githubusercontent.com/46503102/192009240-eeda934f-e5e5-4b0e-9b3c-435cff70e560.png)

Imagine something like that without the background and the text in the center of the image and without typos :D

**Comment by jameshnsears** [comment]
Hi - I've released 4.3.0 (it might take a day or so for it to appear in Google Play / F-Droid): it contains a center option for the Quotation & Source lines.

I wasn't able to combine the Quotation & Source into a single line. As far as I can tell it's not possible to separate a "tap" (two are required: one for the Configuration screen + one for any possible Wikipedia link) between different areas on a block of text that all reside in the same line.

Anyhow, thanks for raising this issue, I think it improves things.

I'll close this issue, but if you spot any related defect please raise a new issue :-)

**Comment by KiritoStorm** [comment]
Thank you, it looks definitely better for me now :heart: 
The only thing that I would change in addition is to also be able to center the text vertically.
So you don't have so much space between the text and the toolbar. :thinking: 

![IMG_20221203_110926](https://user-images.githubusercontent.com/46503102/205435666-1e9790a9-5f1c-4107-907a-669c8df14960.jpg)

A other idea would be to put the author in the next line (if there is one) but I can create seperate issue for that. :)
