### ISSUE TITLE
Feature request: Add support for fortune files

### ISSUE THREAD

**Issue by ChickenOnAStick** [jameshnsears/QuoteUnquote#353]
QuoteUnquote would be more useful if it read fortune files. Fortune files contain the quotes you'll see on a *nix motd, and there are quite a few repos for them floating around, many on Github. They're literally just plaintext files with quotes separated by a newline, a %, and a newline.

See:

https://en.m.wikipedia.org/wiki/Fortune_(Unix)

https://github.com/shlomif/fortune-mod/tree/master/fortune-mod/datfiles

https://github.com/JKirchartz/fortunes

https://github.com/btoll/fortune

**Comment by jameshnsears** [comment]
Hi - thanks for taking the time to suggest this. 

The original idea of the app was to actually use such fortunes, but then I kind of got sidetracked.

I'll attempt to implement a feature to cater for your idea , once I've finished what I'm working on - 4.45.0

I'll update this issue as I progress.

Thanks again :-)

**Comment by jameshnsears** [comment]
Hi - I've just released 4.46.0: it allows for the importing of fortune files.

I've tested the new feature in various ways, but there's still the chance I've missed something - so please let me know if you spot a problem. I'll leave this issue open for a week or so, so feel free to update it if required.

The release will not appear for a few days in F-Droid, but its quicker for Google Play Store.

Thanks for raising this issue - I think it has the potential to make the app useful to more people :-)
