### ISSUE TITLE
Exclude quotes from a given author(s)

### ISSUE THREAD

**Issue by Nikoichu** [jameshnsears/QuoteUnquote#36]
Adding this feature would help people avoid seeing quotes from people, with whose philosophies they don't agree with or whose quotes have no value (I'm looking at you, Shakespeare).

It would work the same as the "All" selection, but would have a field that would accept text input and exclude any quotes, where there are strings that match any words found in the "author" field of the quotes.

For example entering "Shakespeare" would exclude a quote that has "Shakespeare, Hamlet (1600-1601)" in its author field.

**Comment by jameshnsears** [comment]
- Hi - this is a very good idea. But poor old Shakespeare.

The gestures in 4.2.0 is my current priority (which is a reasonable chunk of effort), but the exclusion will follow (bar any bug fixes).

Thank you for suggesting it.

**Comment by jameshnsears** [comment]
OK (finally) - I've released 4.2.0: it includes various changes, one of which is the author (aka Source) exclusion.

It will take a few days for it to appear in Google Play / F-Droid. 

The code passes all my tests; but its still possible I've missed something. So please let me know, via a new GitHub issue) if I have.

Thanks for suggesting this issue, it's definitely improved the app!

**Comment by Nikoichu** [comment]
@jameshnsears Thank you! ❤️
Just got the update, works like a charm. I just cut out a 3000-something of poor ol' Shakespeare's quotes from my list 😄
