### ISSUE TITLE
CSV example in app 

### ISSUE THREAD

**Issue by martin-forum** [jameshnsears/QuoteUnquote#377]
thank you for writing and maintaining this/ your app.

Just one question, can you be more specific about the CSV import. I always get an error message. I am sure its my CSV file. I will continue with try&error.

Any chance that you can add an example in your app directly to the current info text?

I am sure this will help other first-time-user as well.

**Comment by jameshnsears** [comment]
Hi - thanks for taking the time to raise an issue.

I'll update the .csv instructions to be more specific.

In the meantime, please email me - james.hn.sears@gmail.com - a copy of your .csv file and I'll investigate further.

**Comment by jameshnsears** [comment]
Released 4.48.0 + minor instruction improvement.
