### ISSUE TITLE
Ability to copy the quote as text to paste it somewhere else. 

### ISSUE THREAD

**Issue by Itradetime** [jameshnsears/QuoteUnquote#44]
Love your app. I searched in the app for this feature but can't find it. I would like to copy the quote I like from the widget as text. Right now, I just take screenshots but they are not convenient. 

The ideal scenerio would be the ability to copy the text from the app and paste it into my notes app for later access or paste it to word app to be printed. Now if this feature does exist, please point me in the right direction. Thanks again for the app.

**Comment by jameshnsears** [comment]
Hi - thanks for raising the issue.

I believe this feature exists.

In the Configuration > Appearance > Toolbar tab there's an option for "Share". Tick it and the button will appear on the toolbar. 

The "Share" button will allow you to copy the Quotation & Source either into the clipboard or another app.

Let me know either way if this does / doesn't answer you question :-)

**Comment by Itradetime** [comment]
Hi james, 

Thank you for your quick reply and I apologise for my carelessness. I toggled the share button on. 

Deep down, I knew that this feature should be already existing in the app, but I couldn't find it.. Thanks for taking your time to help me, now I can print/save my favourite quotes!  

I would like to add that this app has made a positive impact on my life for a month or so, so thank you for creating this app. Keep inspiring.

**Comment by herrbrixter** [comment]
Android has removed the share to clipboard functionality. The workaround is to install this app:

https://play.google.com/store/apps/details?id=me.thomasvt.sharetoclipboard
