### ISSUE TITLE
[FR] more transition options

### ISSUE THREAD

**Issue by ildar** [jameshnsears/QuoteUnquote#45]
e.g. I'd like bi-hourly, maybe three-hourly changing of quotes.

**Comment by jameshnsears** [comment]
Hi - thanks for raising this request. 

It's an interesting idea.

Just to clarify: you could end up with 48 notifications per day with bi-hourly. That would be acceptable to you?

I've provisionally scheduled this for release 4.5.0 and will start investigating when I hear back from you.

**Comment by ildar** [comment]
bi-hourly is once per 2 hours. I.e. 12 per day.
Thanks

**Comment by jameshnsears** [comment]
OK - thanks for clarifying :-)

The more I think about it the more I like this idea. So thanks for suggesting it.

I'll implement this functionality in version 4.5.0 - which is what I plan to release next, excluding any defect related release.

**Comment by jameshnsears** [comment]
Hi - I just released 4.5.0 to Google Play and F-Droid. It might take up-to three days to appear in these stores, though normally its much quicker.

The release contains a first attempt at this bi-hourly feature.

Let me know if you spot a problem or if it needs fine tuning.

I won't close this issue for a few days, just in case there is something else for either of us to add.

Thanks again for helping improve the app :-)
