### ISSUE TITLE
Broken, reinstall is the only thing that fixes it

### ISSUE THREAD

**Issue by bluechipps** [jameshnsears/QuoteUnquote#5]
**Version of the app**
Version: [e.g.  2.4.0-fdroid]

**Describe the bug**
This is the 2nd time this has happened. Previously I was on an old version, I was hopeful updating would do the trick but looks like the bug still exists. I was just flipping through top quotes sequentially and then after passing about 1000/21794 the widget went blank. Rebooting doesn't fix it either. Below is some evidence which might help diagnose it.

**Screenshots**
[https://drive.google.com/file/d/17RBHvQOZKhFNCNucsZw4tLZwcOOtY6HW/view?usp=drivesdk](https://drive.google.com/file/d/17RBHvQOZKhFNCNucsZw4tLZwcOOtY6HW/view?usp=drivesdk) 

At one point before I recorded the video it displayed a quote in my favorites widget without me ever clicking anything, and it showed "null" for the index. Clicking next at that point made it go blank again.
![Screenshot_20210522-200921_One UI Home](https://user-images.githubusercontent.com/53506/119245327-1931e980-bb3e-11eb-98f4-d3ba470cb01d.jpg)

**Comment by bluechipps** [comment]
If you need me to I can zip up my "databases" folder.

**Comment by jameshnsears** [comment]
I'm apologise that this happened and I'm grateful you took the time to provide such a detailed issue.

I'll take a look into this & have moved this issue onto: https://github.com/jameshnsears/QuoteUnquote/projects/1

If you can zip up the databases and attach it here then that might help.

**Comment by jameshnsears** [comment]
Problem example:

https://user-images.githubusercontent.com/828019/119268751-0500f180-bbfd-11eb-93cf-5bf8bb5d29e5.mp4

**Comment by jameshnsears** [comment]
I have been able to reproduce the defect, so no need for the databases.

**Comment by bluechipps** [comment]
> I have been able to reproduce the defect, so no need for the databases

Great, glad it wasn't too hard to track down.

**Comment by jameshnsears** [comment]
Hi - I've released a fix.

- The googleplay version is already in the Google Play store.
- The fdroid version should take between two and five days to release. 

I've tried to hurry things up for fdroid by removing pending releases - meaning you should jump from 2.4.0 to **2.4.5**, rather than 2.4.1, 2.4.2 etc.

Many thanks for taking the effort to report this issue & apologies for the hassle it caused you.

**Comment by bluechipps** [comment]
No rush, thanks a bunch!
