### ISSUE TITLE
Widget does not remain on home screen

### ISSUE THREAD

**Issue by bharatbhatt762** [jameshnsears/QuoteUnquote#8]
Hi,
I installed the latest version for my Motorola phone Moto G5 S
Android version 8.1.0 .
The widget of quotation can be dragged on home screen but it does not
remain visible once the finger is lifted.

Can you please help.
Best,
Bharat
p.s. it's a wonderful app that you have made
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jameshnsears** [comment]
No launcher - i.e. Nova - involved.

Not repeatable locally: moto g4/7.1; a5/10; f1/11

Happens on f-droid; 
Version 2.6.2-fdroid (77)
+
Version 2.6.0-fdroid (75) 

Possible that happening on -googleplay variant, as 1 user reported something similar.

Might be related to AppCompat theme defects on TextView reported in crashanalytics? HEAD been updated with this in account.

**Comment by jameshnsears** [comment]
Nothing to do with any of the above. After user sending me video I can reproduce...

User not pressing Back button after settings activity. Apparently this is required by SDK for successful placement of widget! I'd always been pressing Back gesture so never spotted this requirement.

User notified + Instructions will be updated in next release.

**Comment by bharatbhatt762** [comment]
Hi James,
For the next version:
Maybe you could have a look at the random button also, using random only goes to the next.
Best,
Bharat

On September 22, 2021 9:57:29 PM GMT+05:30, James HN Sears ***@***.***> wrote:
>Nothing to do with any of the above. User not pressing Back button after settings activity. Apparently this is required by SDK for successful placement of widget! I'd always been pressing Back gesture so never spotted this requirement.
>
>User notified + Instructions will be updated in next release.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jameshnsears/QuoteUnquote/issues/8#issuecomment-925089286
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
